CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER(4) UNIQUE,
    CUSTOMER_NAME VARCHAR2(10) NOT NULL,
    CUSTOMER_TEL VARCHAR2(20),
    CUSTOMER_PASSWORD VARCHAR2(20),
    CUSTOMER_PASSWORD_CHECK VARCHAR2(20),
    CUSTOMER_REMAINED_MONEY NUMBER(10) NOT NULL,
    CUSTOMER_ADDRESS VARCHAR2(40),
    CUSTOMER_IS_MEMBER VARCHAR2(1),
    CUSTOMER_AGE NUMBER(3),
    CONSTRAINT CUSTOMER_TEL_PK PRIMARY KEY(CUSTOMER_TEL)
);

--DROP TABLE SEAT;
--DROP TABLE PRODUCT;
--DROP TABLE ORDERED_PRODUCT;
--DROP TABLE ORDERLIST;
--DROP TABLE CUSTOMER;
CREATE TABLE SEAT(
    SEAT_ID NUMBER(4),
    SEAT_STATE NUMBER(1),
    
    CONSTRAINT SEAT_ID_PK PRIMARY KEY(SEAT_ID)
);

CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(4),
    PRODUCT_NAME VARCHAR2(10),
    PRODUCT_PRICE NUMBER(10),
    
    CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE ORDERED_PRODUCT(
    ORDER_ID NUMBER(4),
    PRODUCT_ID NUMBER(4),
    ORDER_COUNT NUMBER(4),
    
    CONSTRAINT ORDER_ID_PK PRIMARY KEY(ORDER_ID),
    CONSTRAINT ORDER_PRODUCT_ID_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);
CREATE TABLE ORDERLIST(
    ORDERLIST_ID NUMBER(4),
    ORDER_ID NUMBER(4),
    CUSTOMER_TEL VARCHAR2(20),
    ORDER_DATE DATE,
    TOTAL_PRICE NUMBER(4),
    CONSTRAINT ORDERLIST_ID_PK PRIMARY KEY(ORDERLIST_ID),
    CONSTRAINT ORDER_ID_FK FOREIGN KEY(ORDER_ID) REFERENCES ORDERED_PRODUCT(ORDER_ID),
    CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY(CUSTOMER_TEL) REFERENCES CUSTOMER(CUSTOMER_TEL)
);