CREATE TABLE CUSTOMER(
    CUSTOMER_ID NUMBER(10),
    CUSTOMER_NAME VARCHAR2(10),
    CUSTOMER_ADDR VARCHAR2(100),
    CUSTOMER_EMAIL VARCHAR2(100),
    CUSTOMER_PHONENUMBER0 VARCHAR2(20),
    CUSTOMER_PHONENUMBER1 VARCHAR2(20),
    CONSTRAINT CUSTOMER_CUSTOMER_ID_PK PRIMARY KEY(CUSTOMER_ID)
);
--DROP TABLE CUSTOMER;
CREATE TABLE VIDEO(
    VIDEO_ID NUMBER(10),
    VIDEO_GENRE VARCHAR2(10),
    VIDEO_TITLE VARCHAR2(20),
    VIDEO_DIRECTOR VARCHAR2(10),
    VIDEO_ACTOR VARCHAR2(100),
    VIDEO_DETAIL VARCHAR2(1024),
    CONSTRAINT VIDEO_VIDEO_ID_PK PRIMARY KEY(VIDEO_ID)
);
--DROP TABLE VIDEO;
CREATE TABLE VIDEOADMIN(
    VIDEOADMIN_ID NUMBER(10),
    VIDEO_ID NUMBER(10),
    CONSTRAINT VIDEOADMIN_VADMIN_ID_PK PRIMARY KEY(VIDEOADMIN_ID),
    CONSTRAINT VIDEOADMIN_VADMIN_VIDEO_ID_FK FOREIGN KEY(VIDEO_ID) REFERENCES VIDEO(VIDEO_ID)
);
--DROP TABLE VIDEOADMIN;
CREATE TABLE RENTAL(
    RENTAL_ID NUMBER(10),
    RENTAL_RETURNDATE DATE,
    VIDEOADMIN_ID NUMBER(10),
    CUSTOMER_ID NUMBER(10),
    CONSTRAINT RENTAL_RENTAL_ID_PK PRIMARY KEY(RENTAL_ID),
    CONSTRAINT RENTAL_VIDEOADMIN_ID_FK FOREIGN KEY(VIDEOADMIN_ID) REFERENCES VIDEOADMIN(VIDEOADMIN_ID),
    CONSTRAINT RENTAL_CUSTOMER_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
--DROP TABLE RENTAL;