/****************************** TABLE STRUCTURE ******************************/
/***** EMPLOYEE TABLE *****/
CREATE TABLE EMPLOYEE(
    EID VARCHAR2(20),
    EPASSWORD VARCHAR2(20),
    ENAME VARCHAR2(20),
    TEL VARCHAR2(20) UNIQUE,
    SAL  NUMBER(20),
    HIRE_DATE DATE,
    AGE NUMBER(3),
    POSID  NUMBER(2),
    CONSTRAINT EMPLOYEE_EID_PK PRIMARY KEY(EID),
    CONSTRAINT EMPLOYEE_POSID_FK FOREIGN KEY(POSID) REFERENCES POS(POSID)
);
/***** POSITION TABLE *****/
CREATE TABLE POS(
    POSID NUMBER(2),
    POSNAME VARCHAR2(20),
    CONSTRAINT POS_POSID_PK PRIMARY KEY(POSID)
);
//****************************** DROP TABLE ******************************/
DROP TABLE EMPLOYEE;
DROP TABLE POS;
/****************************** TEST ******************************/
/* EMPLOYEE TABLE TEST */scott

INSERT INTO EMPLOYEE(EID, EPASSWORD, ENAME, TEL, SAL, HIRE_DATE, AGE, POSID) VALUES(?, ?, ?, ?, ?, ?, ?);
INSERT INTO EMPLOYEE(EID, EPASSWORD, ENAME, TEL, SAL, HIRE_DATE, AGE, POSID) VALUES('admin', 'admin', 'admin', '00-000-0000', '100000', '200415', 45, 0);
INSERT INTO EMPLOYEE(EID, EPASSWORD, ENAME, TEL, SAL, HIRE_DATE, AGE, POSID) VALUES('abc123', 'abc123', 'aname', '111-1111', '20000', '200416',  30,1);
INSERT INTO EMPLOYEE(EID, EPASSWORD, ENAME, TEL, SAL, HIRE_DATE, AGE, POSID) VALUES('def456', 'def456', 'dname', '222-2222', '10000', '200417', 22, 2);
INSERT INTO EMPLOYEE(EID, EPASSWORD, ENAME, TEL, SAL, HIRE_DATE, AGE, POSID) VALUES('aaa111', 'aaa111', 'aname', '333-3333', '10000', '200417', 20, 2);

SELECT * FROM EMPLOYEE WHERE eid = ?;
SELECT e.eid AS eid, e.epassword AS epassword, e.ename AS ename, e.tel AS tel, e.sal AS sal, e.hire_date AS hire_date, p.posname AS posname FROM EMPLOYEE e INNER JOIN POS p ON e.POSID=p.POSID WHERE e.eid='?';
SELECT * FROM EMPLOYEE WHERE eid = 'admin';
SELECT * FROM EMPLOYEE e INNER JOIN POS p ON e.POSID=p.POSID WHERE e.eid='admin';
SELECT e.eid AS eid, e.epassword AS epassword, e.ename AS ename, e.tel AS tel, e.sal AS sal, e.hire_date AS hire_date, p.posname AS posname FROM EMPLOYEE e INNER JOIN POS p ON e.POSID=p.POSID WHERE e.eid='admin';
/*SEARCH EMPLOYEE*/
SELECT E.ENAME AS ENAME, E.EID AS EID, E.TEL AS ETEL, P.POSNAME AS POSNAME, E.AGE AS EAGE, E.SAL AS SAL, TO_CHAR(E.HIRE_DATE, 'YYYY/MM/DD') AS HIRE_DATE FROM EMPLOYEE E INNER JOIN POS P ON E.POSID=P.POSID WHERE E.ENAME LIKE '%aname%';
SELECT E.ENAME AS ENAME, E.EID AS EID, E.TEL AS ETEL, P.POSNAME AS POSNAME, E.AGE AS EAGE, E.SAL AS SAL, TO_CHAR(E.HIRE_DATE, 'YYYY/MM/DD') AS HIRE_DATE FROM EMPLOYEE E INNER JOIN POS P ON E.POSID=P.POSID WHERE E.EID LIKE '%abc%';
/* POSITION TABLE TEST */
INSERT INTO EMPLOYEE(POSID, POSNAME) VALUES(?, ?);
INSERT INTO POS(POSID, POSNAME) VALUES(0, 'ADMIN');
INSERT INTO POS(POSID, POSNAME) VALUES(1, 'MANAGER');
INSERT INTO POS(POSID, POSNAME) VALUES(2, 'SALESMAN');

